Add model precision to automatically generated submission readme
GATEOverflow/cm4mlops pull request #106
Opened 2024-08-23 20:04 UTC by anandhu-eng

issue: https://github.com/mlcommons/cm4mlops/issues/173

generated submission readme with updation: https://github.com/anandhu-eng/mlperf_inference_test_submissions_v4.1/tree/main/open/MLCommons/measurements/intel_spr_i9-reference-gpu-deepsparse_v1.8.0-default_config/mobilebert-base_quant-none-bert-99/offline

2024-08-28 08:44 UTC, arjunsuresh requested changes

2024-08-28 08:44 UTC, arjunsuresh commented on script/get-mlperf-inference-utils/mlperf_utils.py
> +def get_result_string(version, model, scenario, result_path, has_power, sub_res, model_precision, division="open", system_json=None):
We need to make sure this function is updated everywhere it is called from or make model_precision the last default argument.

2024-09-02 03:10 UTC, anandhu-eng commented on script/get-mlperf-inference-utils/mlperf_utils.py
> +def get_result_string(version, model, scenario, result_path, has_power, sub_res, model_precision, division="open", system_json=None):
Matching the substring `mlperf_utils.get_result_string` or `get_result_string` through `find`, I'm getting only one occurance of the string which is in `generate-mlperf-inference-submission/customize.py`

2024-09-02 03:27 UTC, anandhu-eng commented on script/get-mlperf-inference-utils/mlperf_utils.py
> +def get_result_string(version, model, scenario, result_path, has_power, sub_res, model_precision, division="open", system_json=None):
made changes in commit [d0194dd](https://github.com/GATEOverflow/cm4mlops/pull/106/commits/d0194dda4dadcb3668d36ef8dd170248f3b927c5)

2024-09-02 10:12 UTC, arjunsuresh approved these changes

2024-09-02 10:12 UTC, merged